### PR TITLE
shallow clone instructions added to readme

### PR DESCRIPTION
**Pull request by vlad-sensei**
Added instructions to download repo files though a shallow clone

### CODE REVIEW

**Comment by lillelilje** [comment]
Excuse me if I'm missing something here but wouldn't this have the exact same end result as cloning the whole repo?

**Comment by vlad-sensei** [comment]
Not really:)

[shallow clones](https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones) clone a git repo only up to a specific depth. That is if `--depth 1` is chosen, only the current snapshot will be downloaded without prior history.

By setting `--git-dir=/dev/null` we discard the `.git/` directory and keep only files that are available in the repo.

In practice is it the same as downloading the repo. For me, running
```
git --git-dir=/dev/null clone --depth=1 https://github.com/M-Bab/linux-kernel-amdgpu-binaries
```
downloads all the files and consumes about ~200Mb bandwidth, which is practically the cumulative size of the files.

**Comment by M-Bab** [comment]
What happens on git pull? Does it remain with depth=1 or will it increase in size again?

**Comment by vlad-sensei** [comment]
@M-Bab I think so, however after rebooting the `/tmp` dir will be reset so that the files will not persist. It was my mistake earlier though thinking that `--git-dir=/dev/null` gets rid of the `.git/` directory; will correct it (though it does no harm AFAIK). More explained in this [stackoverflow question](https://stackoverflow.com/questions/11497457/git-clone-without-git-directory).

By the way, thank you for keeping this repo up to date:)

**Pull request merged**
